from __future__ import annotations

"""Automatic Markdown research report generation for every result type."""

from typing import Any, Dict, Iterable


REPORT_BUILD_ID = "research-report-v1-20260714"


def _flatten(payload: Dict[str, Any], prefix: str = "") -> Dict[str, Any]:
    rows: Dict[str, Any] = {}
    for key, value in (payload or {}).items():
        path = f"{prefix}.{key}" if prefix else str(key)
        if isinstance(value, dict):
            rows.update(_flatten(value, path))
        else:
            rows[path] = value
    return rows


def _format_value(value: Any) -> str:
    if value is None:
        return "NA"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        if value != value:
            return "NA"
        if value != 0 and (abs(value) < 1.0e-3 or abs(value) >= 1.0e4):
            return f"{value:.6e}"
        return f"{value:.6g}"
    if isinstance(value, (list, tuple)):
        return ", ".join(_format_value(item) for item in value)
    return str(value).replace("|", "\\|")


def _markdown_table(headers: Iterable[str], rows: Iterable[Iterable[Any]]) -> list[str]:
    header_list = list(headers)
    lines = [
        "| " + " | ".join(header_list) + " |",
        "|" + "|".join("---" for _ in header_list) + "|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(_format_value(value) for value in row) + " |")
    return lines


def _selected_metrics(summary: Dict[str, Any]) -> list[tuple[str, Any]]:
    flat = _flatten(summary)
    preferred = [
        "comparison.efficiency.seeding_efficiency_score",
        "comparison.efficiency.accumulated_rain_enhancement",
        "comparison.efficiency.rain_enhancement_final",
        "comparison.efficiency.rain_onset_time_shift_s",
        "comparison.efficiency.cloud_to_rain_conversion_delta",
        "comparison.research_quality.wet_radius_spectrum.final_number_l1_difference_cm3",
        "comparison.research_quality.wet_radius_spectrum.final_liquid_volume_l1_difference",
        "adapter_summary.final_rain_water_mixing_ratio",
        "adapter_summary.max_rain_water_mixing_ratio",
        "metrics.final_rain_water_mixing_ratio",
        "metrics.max_rain_water_mixing_ratio",
        "ensemble.metrics.rain_water_mixing_ratio_diff_final_mean",
        "n_cases",
        "best_case.ranking_value",
    ]
    return [(key, flat[key]) for key in preferred if key in flat and flat[key] is not None]


def _quality_rows(summary: Dict[str, Any]) -> list[tuple[str, Any]]:
    flat = _flatten(summary)
    suffixes = (
        "water_budget.status",
        "water_budget.max_abs_closed_window_relative_drift_percent",
        "water_budget.max_abs_liquid_partition_residual",
        "wet_radius_spectrum.available",
        "wet_radius_spectrum.final_number_l1_difference_cm3",
        "numerical_convergence.status",
        "numerical_convergence.max_next_finest_relative_difference_percent",
        "growth_pathway_diagnostics_enabled",
    )
    return [
        (key, value)
        for key, value in flat.items()
        if any(key.endswith(suffix) for suffix in suffixes)
    ][:30]


def build_markdown_report(
    *,
    summary: Dict[str, Any],
    metadata: Dict[str, Any],
    validation_rows: list[Dict[str, Any]],
    config: Dict[str, Any],
) -> str:
    """Build a concise, self-documenting report from stored result payloads."""
    experiment_name = metadata.get("experiment_name", summary.get("experiment_name", "experiment"))
    result_type = metadata.get("result_type", summary.get("result_type", "single"))
    lines = [
        f"# {experiment_name} — Research Report",
        "",
        f"> Generated by `{REPORT_BUILD_ID}`. This report summarizes stored outputs; "
        "the CSV/JSON/YAML artifacts remain the source of truth.",
        "",
        "## Run identity",
        "",
    ]
    lines.extend(
        _markdown_table(
            ("Field", "Value"),
            (
                ("Run ID", metadata.get("run_id", summary.get("run_id", "unknown"))),
                ("Created", metadata.get("created_at", "unknown")),
                ("Result type", result_type),
                ("Experiment mode", metadata.get("experiment_mode", summary.get("experiment_mode", "unknown"))),
                ("Adapter", metadata.get("adapter_name", summary.get("adapter_name", "unknown"))),
                ("Case", metadata.get("case_name", summary.get("case_name", "unknown"))),
                ("Random seed", config.get("experiment", {}).get("random_seed", "unknown")),
            ),
        )
    )

    lines.extend(["", "## Research quality gates", ""])
    quality_rows = _quality_rows(summary)
    if quality_rows:
        lines.extend(_markdown_table(("Diagnostic", "Value"), quality_rows))
    else:
        lines.append("No research-quality gate was available in this result version.")

    lines.extend(["", "## Key outcome metrics", ""])
    metrics = _selected_metrics(summary)
    if metrics:
        lines.extend(_markdown_table(("Metric", "Value"), metrics))
    else:
        lines.append("No preferred outcome metric was available.")

    severity_counts = {"error": 0, "warning": 0, "info": 0}
    for row in validation_rows or []:
        severity = str(row.get("severity", "")).lower()
        if severity in severity_counts:
            severity_counts[severity] += 1
    lines.extend(["", "## Configuration validation", ""])
    lines.extend(
        _markdown_table(
            ("Severity", "Count"),
            ((severity, count) for severity, count in severity_counts.items()),
        )
    )

    lines.extend(["", "## Result artifacts", ""])
    result_files = metadata.get("result_files", {})
    if result_files:
        lines.extend(
            _markdown_table(
                ("Role", "Path"),
                ((role, path) for role, path in result_files.items()),
            )
        )
    else:
        lines.append("Artifact manifest unavailable for this result version.")

    lines.extend(
        [
            "",
            "## Reproduction",
            "",
            "1. Use the stored `config.yaml` as the exact run configuration.",
            "2. Review `validation_report.json` before interpreting the result.",
            "3. Confirm adapter/PySDM versions and diagnostic thresholds in `metadata.json`.",
            "4. Re-run with the same random seed and dependency versions.",
            "",
            "## Interpretation constraints",
            "",
            "- `placeholder_warm_cloud` output is synthetic workflow-test data, not physical evidence.",
            "- Cloud/rain labels are instantaneous wet-radius bins, not particle activation histories.",
            "- The seeding injection interval is an open source window in the water-budget diagnostic.",
            "- Numerical convergence is an OFAT next-finest test; near-zero reference metrics require "
            "inspection of absolute differences.",
            "- Diagnostic provenance and threshold robustness should accompany quantitative claims.",
            "",
        ]
    )
    return "\n".join(lines)
